name: Deploy to GH pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1
      
      - name: Setup node ⚙️
        uses: actions/setup-node@v1
      
      - name: Install and Build 🔧
        run: |
          yarn
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: dist
          repository-name: web-edit-db/web-edit-db.github.io
